version: '3.5'

services:

  rabbitmq:
    image: rabbitmq:3-management
    hostname: ecabs-rabbit
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
  network_mode: host